<?php
use Drupal\node\NodeInterface;
use Drupal\node\Entity\Node;
/**
 * Implements hook_node_update().
 */
function pl_topic1task118_node_update(NodeInterface $node) {
  $current_node = Node::load($node->id());
  \Drupal::logger('Node Updates')->notice('Node with title @title of type @type has been updated', [
    '@title' => $current_node->title->getValue()[0]['value'],
    '@type' => $current_node->bundle(),
  ]);
}