<?php

/**
 * Implements hook_entity_view().
 */
function pl_topic13task80_entity_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->bundle() == 'article') {
    $body = $entity->get('body')->value;
    $token = Drupal::token();
    $body = $token->replace($body);
    $entity->set('body', $body);
  }
}
