<?php
use Drupal\Core\Form\FormStateInterface;
/**
 * Implements hook_form_alter().
 */
function pl_topic5task35_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['phone'] = [
    '#type' => 'tel',
    '#title' => 'Enter your phone',
  ];

  $form['#validate'][] = 'pl_topic5task35_settings_validate';
  $form['#submit'][] = 'pl_topic5task35_settings_submit';
}

/**
 * Custom validate a phone number with regexp.
 */
function pl_topic5task35_settings_validate(&$form, FormStateInterface $form_state) {
  $phone_regex = '/^(\+375|80)(29|25|44|33)(\d{3})(\d{2})(\d{2})$/';
  preg_match($phone_regex, $form_state->getValue('phone'), $matches);
  if (empty($matches)) {
    $form_state->setErrorByName('phone', 'Enter correctly phone');
  }
}

/**
 * Custom submit callback.
 */
function pl_topic5task35_settings_submit(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  \Drupal::logger('pl_topic5task32')->notice('Телефон: @phone', [
    '@phone' => $form_state->getValue('phone'),
  ]);
}
